### ISSUE TITLE
Update installation documentation 

### ISSUE THREAD

**Issue by lanerjo** [eligible/knife-bastion#7]
When following the documentation:::
gem install knife-bastion

Then run::: knife bastion start
knife subcommand bastion not found

Fix:::
on Mac:::
sudo /usr/local/bin/chef gem install knife-bastion

Appears that in order for knife to find the bastion subcommand, knife-bastion must be installed using the chef ruby, not the system ruby.

**Comment by kpumuk** [comment]
@lanerjo Does the documentation update look reasonable to you?

**Comment by lanerjo** [comment]
That should make the install for others easier.
I spent about an hour trying to diagnose that issue and found a similar issue for another plugin with the same resolution.
Thank you for a fine product that makes things easier rather than having a dedicated workstation on a box

**Comment by kpumuk** [comment]
I am sorry you had to go through this. We have got a report about troubles with ChefDK a week ago but never got to updating the documentation. Thank you for raising a ticket!
